name: flutter_thermal_printer
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  avprinter:
    path: D:\AVPrinterPlugin

  cupertino_icons: ^1.0.0
  flutter_bloc: ^6.0.5
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.19.0
  avwidget:
    git: https://github.com/anvui/AVWidget.git
  json_serializable: ^3.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/

